name: main.yml
on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  pull-requests: write

env:
  GO_VERSION: 1.24
  GOLANGCI_LINT_VERSION: v2.3.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: anticrew/gh-setup-go@master
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          only-new-issues: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: anticrew/gh-test-go@master
        with:
          go-version: ${{ env.GO_VERSION }}
